name: Remove Repositories from Composer

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  php-code-styling:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Remove repositories from composer.json
        run: |
          FILE="composer.json"

          if grep -q '"repositories":' "$FILE"; then
            echo "Removing repositories object from composer.json"
            jq 'del(.repositories)' "$FILE" > temp.json && mv temp.json "$FILE"
          else
            echo "repositories object not found in composer.json, no changes made."
          fi

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Remove repositories from composer
